/* ============================================================
   ÉDITO — Product Data
   ============================================================ */

const COLOR_MAP = {
  'Black':     '#1A1A1A',
  'White':     '#F5F5F5',
  'Ivory':     '#F5F0E8',
  'Camel':     '#C4A882',
  'Navy':      '#1B3A6B',
  'Cream':     '#FFF8EE',
  'Sage':      '#8A9E8C',
  'Blush':     '#E8B4A4',
  'Charcoal':  '#3D3D3D',
  'Tan':       '#C69B7B',
  'Brown':     '#7C5C3E',
  'Khaki':     '#BFB08A',
  'Olive':     '#6B7040',
  'Grey':      '#9E9E9E',
  'Blue':      '#4A7BBF',
  'Red':       '#B83232',
  'Natural':   '#D4C9B4',
  'Bordeaux':  '#7B2340',
  'Ecru':      '#EDE3D0',
  'Stone':     '#C4BFAF',
};

const PRODUCTS = [
  /* ── WOMEN ─────────────────────────────── */
  {
    id: 1,
    name: 'Structured Wool Blazer',
    category: 'women',
    subcategory: 'Outerwear',
    price: 189,
    originalPrice: null,
    colors: ['Camel', 'Black', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A masterfully tailored blazer in premium wool blend. Notched lapels, welt pockets, and a clean single-button closure define this refined silhouette. The structured shoulder and nipped waist create an enduring, polished look.',
    images: [
      'https://picsum.photos/seed/w-blazer-a/600/800',
      'https://picsum.photos/seed/w-blazer-b/600/800',
    ],
    tags: ['New', 'Featured'],
    featured: true,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 2,
    name: 'Midi Slip Dress',
    category: 'women',
    subcategory: 'Dresses',
    price: 145,
    originalPrice: null,
    colors: ['Black', 'Ivory', 'Blush'],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Fluid satin-finish midi dress with adjustable spaghetti straps, a delicate lace trim hem, and bias-cut construction that drapes elegantly on the body. A versatile piece that transitions from day to evening effortlessly.',
    images: [
      'https://picsum.photos/seed/w-dress-a/600/800',
      'https://picsum.photos/seed/w-dress-b/600/800',
    ],
    tags: ['New'],
    featured: false,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 3,
    name: 'Wide Leg Tailored Trousers',
    category: 'women',
    subcategory: 'Bottoms',
    price: 99,
    originalPrice: null,
    colors: ['Cream', 'Black', 'Camel'],
    sizes: ['36', '38', '40', '42', '44'],
    description: 'High-waisted trousers with a fluid wide leg silhouette crafted from a lightweight crepe fabric. Features a concealed zip, front pleats, and full-length cut that elongates the figure.',
    images: [
      'https://picsum.photos/seed/w-trousers-a/600/800',
      'https://picsum.photos/seed/w-trousers-b/600/800',
    ],
    tags: ['Bestseller'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: true,
  },
  {
    id: 4,
    name: 'Fine Knit Cardigan',
    category: 'women',
    subcategory: 'Knitwear',
    price: 115,
    originalPrice: null,
    colors: ['Ivory', 'Camel', 'Sage'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Luxuriously soft fine-knit cardigan in a relaxed, longline silhouette. Features mother-of-pearl buttons, ribbed cuffs, and hem. A wardrobe cornerstone that pairs beautifully with everything.',
    images: [
      'https://picsum.photos/seed/w-cardigan-a/600/800',
      'https://picsum.photos/seed/w-cardigan-b/600/800',
    ],
    tags: [],
    featured: false,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 5,
    name: 'Tailored Wool Coat',
    category: 'women',
    subcategory: 'Outerwear',
    price: 299,
    originalPrice: null,
    colors: ['Camel', 'Black', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'An impeccably crafted double-faced wool coat with a clean, minimal silhouette. Large lapels, structured shoulders, and a self-tie belt create a quintessentially elegant outer layer that will last for decades.',
    images: [
      'https://picsum.photos/seed/w-coat-a/600/800',
      'https://picsum.photos/seed/w-coat-b/600/800',
    ],
    tags: ['Featured'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 6,
    name: 'Ribbed Turtleneck',
    category: 'women',
    subcategory: 'Tops',
    price: 65,
    originalPrice: 89,
    colors: ['Black', 'Ivory', 'Camel'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Slim-fit ribbed turtleneck in a soft viscose blend. A refined essential that layers perfectly under blazers and coats, or stands alone as a polished look with tailored trousers.',
    images: [
      'https://picsum.photos/seed/w-turtle-a/600/800',
      'https://picsum.photos/seed/w-turtle-b/600/800',
    ],
    tags: ['Sale'],
    featured: false,
    isNew: false,
    isSale: true,
    isBestseller: false,
  },
  {
    id: 7,
    name: 'Flowy Maxi Skirt',
    category: 'women',
    subcategory: 'Bottoms',
    price: 99,
    originalPrice: null,
    colors: ['Sage', 'Black', 'Ecru'],
    sizes: ['36', '38', '40', '42', '44'],
    description: 'Fluid maxi skirt in a lightweight georgette fabric. Features an elastic waistband, subtle A-line silhouette, and delicate movement. Effortlessly elegant for any occasion.',
    images: [
      'https://picsum.photos/seed/w-skirt-a/600/800',
      'https://picsum.photos/seed/w-skirt-b/600/800',
    ],
    tags: ['New'],
    featured: false,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 8,
    name: 'Silk Blouse',
    category: 'women',
    subcategory: 'Tops',
    price: 129,
    originalPrice: null,
    colors: ['Ivory', 'Bordeaux', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Relaxed silk blouse with a V-neckline, subtle pleated front, and slightly oversized silhouette. Crafted from pure silk that moves beautifully and provides a timeless elegance.',
    images: [
      'https://picsum.photos/seed/w-silk-a/600/800',
      'https://picsum.photos/seed/w-silk-b/600/800',
    ],
    tags: ['New', 'Bestseller'],
    featured: true,
    isNew: true,
    isSale: false,
    isBestseller: true,
  },
  {
    id: 9,
    name: 'Leather Crossbody Bag',
    category: 'accessories',
    subcategory: 'Bags',
    price: 219,
    originalPrice: null,
    colors: ['Tan', 'Black'],
    sizes: ['One Size'],
    description: 'Structured crossbody bag in full-grain leather with a polished gold-tone clasp. Features a detachable chain strap, interior zip pocket, and card slots. A refined companion for every occasion.',
    images: [
      'https://picsum.photos/seed/acc-bag-a/600/800',
      'https://picsum.photos/seed/acc-bag-b/600/800',
    ],
    tags: ['Featured'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },

  /* ── MEN ────────────────────────────────── */
  {
    id: 10,
    name: 'Oxford Button-Down Shirt',
    category: 'men',
    subcategory: 'Shirts',
    price: 79,
    originalPrice: 105,
    colors: ['White', 'Blue', 'Charcoal'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Impeccably fitted Oxford cloth shirt with a classic button-down collar. Features chest pocket and a slightly tapered body that sits perfectly whether tucked or untucked.',
    images: [
      'https://picsum.photos/seed/m-shirt-a/600/800',
      'https://picsum.photos/seed/m-shirt-b/600/800',
    ],
    tags: ['Sale'],
    featured: false,
    isNew: false,
    isSale: true,
    isBestseller: false,
  },
  {
    id: 11,
    name: 'Slim Wool Trousers',
    category: 'men',
    subcategory: 'Trousers',
    price: 109,
    originalPrice: null,
    colors: ['Charcoal', 'Navy', 'Camel'],
    sizes: ['30', '32', '34', '36', '38'],
    description: 'Tailored slim-fit trousers in a fine wool blend with a subtle twill weave. Mid-rise waist, side pockets, and slim straight leg. The cornerstone of a refined wardrobe.',
    images: [
      'https://picsum.photos/seed/m-trousers-a/600/800',
      'https://picsum.photos/seed/m-trousers-b/600/800',
    ],
    tags: ['Bestseller'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: true,
  },
  {
    id: 12,
    name: 'Unstructured Wool Blazer',
    category: 'men',
    subcategory: 'Outerwear',
    price: 249,
    originalPrice: null,
    colors: ['Navy', 'Charcoal', 'Camel'],
    sizes: ['46', '48', '50', '52', '54'],
    description: 'Soft-shoulder blazer in a fine Italian wool. The unstructured construction offers a relaxed drape while maintaining a polished silhouette. Patch pockets and horn buttons add authentic craftsmanship.',
    images: [
      'https://picsum.photos/seed/m-blazer-a/600/800',
      'https://picsum.photos/seed/m-blazer-b/600/800',
    ],
    tags: ['Featured'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 13,
    name: 'Merino Crewneck',
    category: 'men',
    subcategory: 'Knitwear',
    price: 125,
    originalPrice: null,
    colors: ['Camel', 'Navy', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Fine merino wool crewneck in a classic relaxed fit. Garment-washed for extra softness with ribbed collar, cuffs, and hem. The most refined version of a wardrobe essential.',
    images: [
      'https://picsum.photos/seed/m-merino-a/600/800',
      'https://picsum.photos/seed/m-merino-b/600/800',
    ],
    tags: ['New'],
    featured: false,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 14,
    name: 'Slim Chinos',
    category: 'men',
    subcategory: 'Trousers',
    price: 89,
    originalPrice: 119,
    colors: ['Khaki', 'Charcoal', 'Olive'],
    sizes: ['30', '32', '34', '36', '38'],
    description: 'Precision-cut slim chinos in a premium stretch cotton. A modern mid-rise with a tapered leg that works seamlessly from weekend to office. Durable and elegant in equal measure.',
    images: [
      'https://picsum.photos/seed/m-chinos-a/600/800',
      'https://picsum.photos/seed/m-chinos-b/600/800',
    ],
    tags: ['Sale'],
    featured: false,
    isNew: false,
    isSale: true,
    isBestseller: false,
  },
  {
    id: 15,
    name: 'Wool Overcoat',
    category: 'men',
    subcategory: 'Outerwear',
    price: 359,
    originalPrice: null,
    colors: ['Charcoal', 'Camel', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'A commanding double-breasted overcoat in heavyweight pure wool. Full-length silhouette, notched lapels, and a clean minimalist design that stands as the ultimate cold-weather statement piece.',
    images: [
      'https://picsum.photos/seed/m-overcoat-a/600/800',
      'https://picsum.photos/seed/m-overcoat-b/600/800',
    ],
    tags: ['Featured'],
    featured: true,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 16,
    name: 'Leather Derby Shoes',
    category: 'men',
    subcategory: 'Footwear',
    price: 189,
    originalPrice: null,
    colors: ['Brown', 'Black'],
    sizes: ['40', '41', '42', '43', '44', '45'],
    description: 'Classic Derby shoes in full-grain calf leather with a Goodyear-welted construction for exceptional durability. The sleek, rounded toe and leather sole offer timeless sophistication.',
    images: [
      'https://picsum.photos/seed/m-shoes-a/600/800',
      'https://picsum.photos/seed/m-shoes-b/600/800',
    ],
    tags: ['Bestseller'],
    featured: false,
    isNew: false,
    isSale: false,
    isBestseller: true,
  },

  /* ── ACCESSORIES ────────────────────────── */
  {
    id: 17,
    name: 'Cashmere Scarf',
    category: 'accessories',
    subcategory: 'Scarves',
    price: 129,
    originalPrice: null,
    colors: ['Camel', 'Ivory', 'Grey'],
    sizes: ['One Size'],
    description: 'Exquisitely soft scarf in pure cashmere with a delicate fringe finish. A generous 180cm length offers versatile styling options. The definitive cold-weather luxury.',
    images: [
      'https://picsum.photos/seed/acc-scarf-a/600/800',
      'https://picsum.photos/seed/acc-scarf-b/600/800',
    ],
    tags: ['Bestseller'],
    featured: false,
    isNew: false,
    isSale: false,
    isBestseller: true,
  },
  {
    id: 18,
    name: 'Leather Belt',
    category: 'accessories',
    subcategory: 'Belts',
    price: 55,
    originalPrice: null,
    colors: ['Black', 'Tan', 'Brown'],
    sizes: ['75', '80', '85', '90', '95'],
    description: 'A refined leather belt in full-grain cowhide with a polished pin-buckle closure. Minimal and enduring, the perfect finishing detail for tailored trousers or jeans.',
    images: [
      'https://picsum.photos/seed/acc-belt-a/600/800',
      'https://picsum.photos/seed/acc-belt-b/600/800',
    ],
    tags: [],
    featured: false,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 19,
    name: 'Leather Bifold Wallet',
    category: 'accessories',
    subcategory: 'Small Leather Goods',
    price: 75,
    originalPrice: null,
    colors: ['Black', 'Brown', 'Tan'],
    sizes: ['One Size'],
    description: 'Slim bifold wallet in smooth, full-grain leather with eight card slots, a note compartment, and an interior coin pocket. A considered object that improves with age.',
    images: [
      'https://picsum.photos/seed/acc-wallet-a/600/800',
      'https://picsum.photos/seed/acc-wallet-b/600/800',
    ],
    tags: [],
    featured: false,
    isNew: false,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 20,
    name: 'Silk Square Scarf',
    category: 'accessories',
    subcategory: 'Scarves',
    price: 85,
    originalPrice: 119,
    colors: ['Ivory', 'Blue', 'Red'],
    sizes: ['One Size'],
    description: 'Luxurious 90×90cm silk twill square scarf with a hand-rolled edge and exclusive geometric print. Wear as a hair scarf, neck piece, or bag accent for a distinctly editorial look.',
    images: [
      'https://picsum.photos/seed/acc-silkscarf-a/600/800',
      'https://picsum.photos/seed/acc-silkscarf-b/600/800',
    ],
    tags: ['Sale', 'New'],
    featured: false,
    isNew: true,
    isSale: true,
    isBestseller: false,
  },
  {
    id: 21,
    name: 'Canvas Tote',
    category: 'accessories',
    subcategory: 'Bags',
    price: 69,
    originalPrice: null,
    colors: ['Natural', 'Black'],
    sizes: ['One Size'],
    description: 'Heavyweight canvas tote with leather handles and base reinforcement. Generous interior with a zip inner pocket and ÉDITO embossed stamp. Effortlessly practical with an editorial soul.',
    images: [
      'https://picsum.photos/seed/acc-tote-a/600/800',
      'https://picsum.photos/seed/acc-tote-b/600/800',
    ],
    tags: ['New'],
    featured: false,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 22,
    name: 'Merino Wool Dress',
    category: 'women',
    subcategory: 'Dresses',
    price: 169,
    originalPrice: null,
    colors: ['Black', 'Stone', 'Bordeaux'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegant midi dress in extra-fine merino wool. Long sleeves, V-neck with delicate button placket, and a flared skirt that moves beautifully. A versatile piece that works across all seasons.',
    images: [
      'https://picsum.photos/seed/w-merinodress-a/600/800',
      'https://picsum.photos/seed/w-merinodress-b/600/800',
    ],
    tags: ['New', 'Featured'],
    featured: true,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 23,
    name: 'Relaxed Linen Shirt',
    category: 'men',
    subcategory: 'Shirts',
    price: 89,
    originalPrice: null,
    colors: ['White', 'Ecru', 'Sage'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Relaxed-fit linen shirt with a point collar, front chest pocket, and slightly longer back hem. Stone-washed for a lived-in texture that only improves with each wear.',
    images: [
      'https://picsum.photos/seed/m-linen-a/600/800',
      'https://picsum.photos/seed/m-linen-b/600/800',
    ],
    tags: ['New'],
    featured: false,
    isNew: true,
    isSale: false,
    isBestseller: false,
  },
  {
    id: 24,
    name: 'Knit Bucket Hat',
    category: 'accessories',
    subcategory: 'Hats',
    price: 45,
    originalPrice: 65,
    colors: ['Black', 'Camel', 'Ivory'],
    sizes: ['One Size'],
    description: 'Fine-knit bucket hat in a warm cashmere-blend yarn. A playful editorial accessory with understated construction. The perfect off-duty complement to structured pieces.',
    images: [
      'https://picsum.photos/seed/acc-hat-a/600/800',
      'https://picsum.photos/seed/acc-hat-b/600/800',
    ],
    tags: ['Sale'],
    featured: false,
    isNew: false,
    isSale: true,
    isBestseller: false,
  },
];
